exclude: index.html, MSWordColors.html, planetsdata.html, resume.html, style.css
timezone: America/Chicago
encoding: utf-8
title: Take ℵ₀
description: Random opinions from another nerd
theme: jekyll-theme-midnight
baseurl: /quickpages
