exclude: index.html, MSWordColors.html, planetsdata.html, resume.html, style.css
timezone: America/Chicago
encoding: utf-8
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
title: Take ℵ₀
description: Random opinions from another nerd
